branch-defaults:
  deafault:
    environment: null
  deafualt:
    environment: null
    group_suffix: null
  default:
    environment: imdb-clone-env-dev
    group_suffix: null
environment-defaults:
  imdb-clone-env:
    branch: default
    repository: IMDB_CLONE_FYND
  imdb-clone-env-dev:
    branch: default
    repository: IMDB_CLONE_FYND
global:
  application_name: imdb-clone-app
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
